export const categories = {
  Men: [
    { name: "Select", price: 0 },
    { name: "Men shirt", price: 20 },
    { name: "Starch shirt", price: 30 },
    { name: "T-shirt", price: 20 },
    { name: "Pant", price: 20 },
    { name: "Jeans pant", price: 20 },
    { name: "Silk shirt", price: 30 },
    { name: "Dhoti", price: 20 },
    { name: "Pancha", price: 20 },
    { name: "Pattu pancha", price: 50 },
    { name: "Pipancha", price: 15 },
    { name: "Short", price: 20 },
    { name: "Kurta", price: 20 },
    { name: "Night pant", price: 20 },
    { name: "Men woolen", price: 30 },
    { name: "Coat", price: 60 },
    { name: "Waistcoat", price: 20 },
    { name: "Long coat", price: 60 },
    { name: "Jacket", price: 60 },
    { name: "Hoodie", price: 30 },
    { name: "Leather jacket", price: 100 },
    { name: "Sweat shirt", price: 60 },
    { name: "Sweater", price: 60 },
    { name: "Kurta heavy", price: 30 },
    { name: "Safari suit coat", price: 60 },
    { name: "Capri", price: 20 },
    { name: "Sweat pant", price: 30 },
    { name: "Track pant", price: 30 },
    { name: "Swimming dress", price: 20 },
    { name: "Underwears", price: 15 },
  ],

  Women: [
    { name: "Select", price: 0 },
    { name: "Kurta plane", price: 20 },
    { name: "Starch ladies dress", price: 30 },
    { name: "Salwar plain", price: 20 },
    { name: "Top plane", price: 20 },
    { name: "Dupatta", price: 10 },
    { name: "Legging", price: 20 },
    { name: "Dress bottom", price: 20 },
    { name: "Saree plain", price: 25 },
    { name: "Blouse", price: 5 },
    { name: "Plazo plane", price: 20 },
    { name: "Petticoat", price: 10 },
    { name: "Dress set", price: 50 },
    { name: "Kurta heavy", price: 60 },
    { name: "Salwar very heavy", price: 40 },
    { name: "Plazo very heavy", price: 40 },
    { name: "Dupatta heavy", price: 30 },
    { name: "Pattu saree", price: 40 },
    { name: "Work saree", price: 60 },
    { name: "Blouse heavy", price: 15 },
    { name: "Dress set heavy", price: 75 },
    { name: "Dress set long", price: 50 },
    { name: "Dress set long heavy", price: 100 },
    { name: "Lehenga set plain", price: 70 },
    { name: "Lehenga set heavy", price: 100 },
    { name: "Bridal lehenga set", price: 200 },
    { name: "Bridal lehenga blouse", price: 50 },
    { name: "skirt plain", price: 20 },
    { name: "skirt heavy", price: 50 },
    { name: "Top heavy", price: 50 },
    { name: "Shirt", price: 20 },
    { name: "T-shirt", price: 20 },
    { name: "Pant", price: 20 },
    { name: "Jeans", price: 20 },
    { name: "Capri", price: 20 },
    { name: "Stole", price: 10 },
    { name: "Court", price: 50 },
    { name: "Jacket", price: 35 },
    { name: "Sweater", price: 50 },
    { name: "Track pant", price: 20 },
    { name: "Scarf", price: 20 },
    { name: "Jumper", price: 50 },
    { name: "Dangre", price: 20 },
    { name: "Slacks", price: 20 },
    { name: "Shawl", price: 20 }, // matched to "Shawl"
    { name: "Long coat", price: 45 },
    { name: "Kudi", price: 35 },
    { name: "Long pullover", price: 50 },
    { name: "Stocking", price: 10 },
    { name: "Sweat shirt with hoodie", price: 35 },
    { name: "Nighties", price: 20 },
  ],

  kids: [
    { name: "Select", price: 0 },
    { name: "T-shirt", price: 15 },
    { name: "Starch saree", price: 40 },
    { name: "Shirt", price: 15 },
    { name: "Pant", price: 15 },
    { name: "Jeans", price: 15 },
    { name: "Frock", price: 15 },
    { name: "Skirt", price: 15 },
    { name: "Top", price: 15 },
    { name: "Long top", price: 15 },
    { name: "Shorts", price: 15 },
    { name: "Capri", price: 15 },
    { name: "Kurta plane", price: 15 },
    { name: "Salwar plain", price: 15 },
    { name: "Blouse", price: 15 },
    { name: "Dress set plain", price: 30 },
    { name: "Dress set heavy", price: 50 },
    { name: "Dupatta plane", price: 15 },
    { name: "Dupatta heavy", price: 20 },
    { name: "Legging", price: 15 },
    { name: "Frock heavy", price: 40 },
    { name: "Skirt heavy", price: 40 },
    { name: "Sherwani set", price: 75 },
    { name: "Kurta heavy", price: 30 },
    { name: "Salwar heavy", price: 30 },
    { name: "Blouse heavy", price: 25 },
    { name: "Lehenga", price: 50 },
    { name: "Lehenga heavy", price: 75 },
    { name: "Coat", price: 40 }, // your list says "Court", corrected to Coat
    { name: "Waistcoat", price: 20 },
    { name: "Jacket", price: 25 },
    { name: "Sweater", price: 30 },
    { name: "Track pant", price: 20 },
    { name: "Socks pair", price: 10 },
    { name: "Baby blanket", price: 30 },
  ],

  Household: [
    { name: "Select", price: 0 },
    { name: "Towels", price: 20 },
    { name: "Blanket", price: 50 },
    { name: "Bed sheet", price: 30 },
    { name: "Pillow covers set", price: 10 },
    { name: "Bathrobe", price: 50 },
    { name: "Hand kerchief", price: 10 },
    { name: "Muffler", price: 20 },
    { name: "Tie", price: 10 },
    { name: "Uniform set", price: 50 },
    { name: "Sofa covers", price: 50 },
  ],
};
